version: "3.9"
services:
    db:
        container_name: redis
        image: redis/redis-stack
        restart: unless-stopped
        volumes:
            - ./data:/data
    server:
        container_name: server
        image: registry.digitalocean.com/yavsrg/interlude-web-server
        restart: unless-stopped
        ports:
            - 32767:32767
            - 443:443
        depends_on:
            - db
        volumes:
            - ./secrets:/docker_root/secrets